#!usr/bin/env python
from flask import Flask, jsonify, abort, make_response, g, request, render_template, redirect, url_for, send_from_directory
import json
from flask_cors import CORS
from bs4 import BeautifulSoup



app = Flask(__name__)
CORS(app)



#  Parser
def generateFormPayloads(url, htmlCode):
    # Parse HTML code using BeautifulSoup
    soup = BeautifulSoup(htmlCode, 'html.parser')

    # Find all form elements
    forms = soup.find_all('form')


    fetchScripts       = []
    payloadInstruction = []


    print("** Performing static analysis on scraped HTML...")

    # Iterate through each form
    for form in forms:
        print("++ Form identified")

        # Flip finders flags to false here
        hasRadioButtons = False


        form_id = form.get('id', '')
        form_action = form.get('action', '')
        form_method = form.get('method', 'GET').upper()

        formData = {}

        radioButtonData = {}

        # Look for form data
        for inputTag in form.find_all('input'):
            # Need to skip the submit input
            inputType = inputTag.get('type')

            inputName  = inputTag.get('name')
            inputValue = inputTag.get('value', '')

            # Need special handling of some input types
            if inputType == 'submit':
            	continue

            if inputType == 'radio':
                # Get the choices
                hasRadioButtons = True
                if inputName in radioButtonData:
                    radioButtonData[inputName].append(inputValue)
                else:
                    radioButtonData[inputName] = [inputValue]

                for name, values in radioButtonData.items():
                    print(f"RadioButton name: {name}")
                    for value in values:
                        print(f"Value: {value}")

            # print("!! parsing: " + inputName + ', ' + inputValue)
            formData[inputName] = inputValue

            # What about inputs that might not necessarily be listed as an input?
            # select
            for select in form.find_all('select'):
                name = select.get('name')
                options = select.find_all('option')
                for option in options:
                    print("For select: " + name + ", found option: " + option['value'])


        # Fix action if empty (defaults to same page)
        if form_action == '':
            form_action = url

        # Construct JavaScript code for Fetch API
        fetchScript = f"""
// Payload autogenerated by JS-Tap
// Form name: {form_id}
"""

        bodyString   = 'body: `'
        headerString = "{'Content-Type':'application/x-www-form-urlencoded'},"
        counter = 0

        for name, value in formData.items():
            if (counter == 0):
               bodyString += name + '=' + value + '\n'
            else:
               bodyString += '&' + name + '=' + value

               # Check for 
               bodyString += '\n'
            counter += 1

        bodyString = bodyString[:-1]
        bodyString += "`"

        print("*** Body string:")
        print(bodyString)

        fetchScript += f"""
fetch('{form_action}', {{
method: '{form_method}',
headers: {headerString}
{bodyString}
}})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
"""

        print("------")
        print("Generated script:")
        print(fetchScript)

        fetchScripts.append(fetchScript)

        # Figure out the instructions/description for this payload
        instructions = "Payload Instruction:\n"
        instructions += "Fill our the form values in the JavaScript payload.\n"
        instructions += "Looking at the screenshot can likely help figure out the required fields.\n"
        instructions += "Guidance for particular inputs can be found in the instructions below where possible.\n\n"

        if hasRadioButtons:
            instructions += "Radio button input tips:\n"
            for name, values in radioButtonData.items():
                instructions += f"  RadioButton name: {name}\n"
                for value in values:
                    instructions += f"    Value: {value}\n"
                instructions += "\n"



        print(instructions)
        print("--------")

    return





@app.route('/', methods=['GET'])
def sendIndex():
	with open('./testIndex.html', 'rb') as file:
		page = file.read()
		response = make_response(page, 200)

		return response


@app.route('/form', methods=['POST'])
def catchForm():
    for key, value in request.form.items():
        print(f'Name: {key}, Value: {value}')

    return "ok", 200


if __name__ == '__main__':
	with open('./testIndex.html', 'rb') as file:
		htmlCode = file.read()
		generateFormPayloads('/form', htmlCode)

	app.run(debug=False, host='0.0.0.0', port=8888)


