#!usr/bin/env python
from flask import Flask, jsonify, abort, make_response, g, request, render_template, redirect, url_for, send_from_directory
import json
from flask_cors import CORS
from bs4 import BeautifulSoup



app = Flask(__name__)
CORS(app)



#  Parser
def generateFormPayloads(url, htmlCode):
    # Parse HTML code using BeautifulSoup
    soup = BeautifulSoup(htmlCode, 'html.parser')

    # Find all form elements
    forms = soup.find_all('form')


    fetch_scripts = []

    print("** Performing static analysis on scraped HTML...")

    # Iterate through each form
    for form in forms:
        print("++ Form identified")
        form_id = form.get('id', '')
        form_action = form.get('action', '')
        form_method = form.get('method', 'GET').upper()

        # print("HTML:")
        # print(form)
        # print("*********")
        formData = {}
        # Look for form data
        for inputTag in form.find_all('input'):
            # Need to skip the submit input
            inputType = inputTag.get('type')

            if inputType == 'submit':
            	continue

            inputName = inputTag.get('name')
            inputValue = inputTag.get('value', '')



            print("!! parsing: " + inputName + ', ' + inputValue)
            formData[inputName] = inputValue


        # Fix action if empty (defaults to same page)
        if form_action == '':
            form_action = url

        # Construct JavaScript code for Fetch API
        fetch_script = f"""
        // Payload autogenerated by JS-Tap
        // Form name: {form_id}
        """

        bodyString = 'body: "'

        for name, value in formData.items():
            bodyString += name + '=' + value + '&'
            # fetch_script += f"formData.append('{name}', '{value}');\n"

        bodyString = bodyString[:-1]

        # print("*** Body string:")
        print(bodyString)

        fetch_script += f"""
        fetch('{form_action}', {{
            method: '{form_method}',
            '{bodyString}'
        }})
        .then(response => response.json())
        .then(data => console.log(data))
        .catch(error => console.error('Error:', error));
        """


        # fetch_script = f"""
        #     // Payload autogenerated by JS-Tap
        #     // Form name: {form_id}
        #     fetch('{form_action}', {{
        #         method: '{form_method}',
        #         body: new FormData(document.getElementById('{form_id}'))
        #     }})
        #     .then(response => response.json())
        #     .then(data => console.log(data))
        #     .catch(error => console.error('Error:', error));
        # """

        print("------")
        print("Generated script:")
        print(fetch_script)

        fetch_scripts.append(fetch_script)

    return





@app.route('/', methods=['GET'])
def sendIndex():
	with open('./testIndex.html', 'rb') as file:
		page = file.read()
		response = make_response(page, 200)

		return response


@app.route('/form', methods=['POST'])
def catchForm():
	for key, value in request.form.items():
		print(f'Name: {key}, Value: {value}')

	return "ok", 200


if __name__ == '__main__':
	with open('./testIndex.html', 'rb') as file:
		htmlCode = file.read()
		generateFormPayloads('/form', htmlCode)

	app.run(debug=False, host='0.0.0.0', port=8888)


